# Default values for golang.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
deployment:
  name: hello-world
image:
  pullPolicy: IfNotPresent
  repository: r.cfcr.io/anna-codefresh/helm-sample-app-go
service:
  name: my-example-helm-app
  type: LoadBalancer
  externalPort: 80
  internalPort: 8080
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
ingress:
  enabled: false

secrets:
  database_url: 'my database connection url'
  allowed_hosts: '*'
  secret_key: '8298kj@#$%*(9823797jsadk928'

environments:
  - name: DATABASE_URL
    value: 'my database connection url'
  - name: ALLOWED_HOSTS
    value: '*'
  - name: SECRET_KEY
    value: '8298kj@#$%*(9823797jsadk928'
